--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2
-- Dumped by pg_dump version 16.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO postgres;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Authentication; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Authentication" (
    authenticationid bigint NOT NULL,
    password character varying
);


ALTER TABLE public."Authentication" OWNER TO postgres;

--
-- Name: Authentication_authenticationid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Authentication" ALTER COLUMN authenticationid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Authentication_authenticationid_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: BankingCredentials; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."BankingCredentials" (
    bankingcredentialsid bigint NOT NULL,
    bankingcredentialsie boolean,
    bankingcredentialskpp character varying,
    bankingcredentialsinn character varying,
    bankingcredentialsbic character varying,
    bankingcredentialskpo character varying,
    bankingcredentialsogrn character varying,
    bankingcredentialsfax character varying,
    bankingcredentialsphone character varying,
    bankingcredentialsbank character varying
);


ALTER TABLE public."BankingCredentials" OWNER TO postgres;

--
-- Name: BankingCredentials_bankingcredentialsid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."BankingCredentials" ALTER COLUMN bankingcredentialsid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."BankingCredentials_bankingcredentialsid_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Client; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Client" (
    clientid bigint NOT NULL,
    clientname character varying,
    bankingcredentialsid bigint
);


ALTER TABLE public."Client" OWNER TO postgres;

--
-- Name: Client_clientid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Client" ALTER COLUMN clientid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Client_clientid_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Dilivery; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Dilivery" (
    diliveryid bigint NOT NULL,
    diliveryneeded boolean,
    diliveryadress character varying,
    diliverytime timestamp without time zone,
    diliverytypeid bigint
);


ALTER TABLE public."Dilivery" OWNER TO postgres;

--
-- Name: DiliveryType; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."DiliveryType" (
    diliverytypeid bigint NOT NULL,
    diliverytypename character varying
);


ALTER TABLE public."DiliveryType" OWNER TO postgres;

--
-- Name: DiliveryType_diliverytypeid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."DiliveryType" ALTER COLUMN diliverytypeid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."DiliveryType_diliverytypeid_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Dilivery_diliveryid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Dilivery" ALTER COLUMN diliveryid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Dilivery_diliveryid_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Distributor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Distributor" (
    distributorid bigint NOT NULL,
    distributorname character varying,
    bankingcredentialsid bigint
);


ALTER TABLE public."Distributor" OWNER TO postgres;

--
-- Name: Distributor_distributorid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Distributor" ALTER COLUMN distributorid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Distributor_distributorid_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Order; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Order" (
    orderid bigint NOT NULL,
    orderdescription character varying,
    ordertime timestamp without time zone,
    ordertotalprice numeric,
    clientid bigint,
    diliveryid bigint
);


ALTER TABLE public."Order" OWNER TO postgres;

--
-- Name: Order_orderid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Order" ALTER COLUMN orderid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Order_orderid_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: OrderedProducts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."OrderedProducts" (
    orderedproductsid bigint NOT NULL,
    orderid bigint,
    productid bigint,
    orderedproductscount integer
);


ALTER TABLE public."OrderedProducts" OWNER TO postgres;

--
-- Name: OrderedProducts_orderedproductsid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."OrderedProducts" ALTER COLUMN orderedproductsid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."OrderedProducts_orderedproductsid_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Position; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Position" (
    positionid integer NOT NULL,
    positionname character varying
);


ALTER TABLE public."Position" OWNER TO postgres;

--
-- Name: Position_positionid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Position" ALTER COLUMN positionid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Position_positionid_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Product" (
    productid bigint NOT NULL,
    warehouseid bigint,
    typeid bigint,
    distributorid bigint,
    specificationid bigint,
    productname character varying,
    productarrival timestamp without time zone,
    productinwarehouse boolean
);


ALTER TABLE public."Product" OWNER TO postgres;

--
-- Name: Product_productid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Product" ALTER COLUMN productid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Product_productid_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Size; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Size" (
    sizeid bigint NOT NULL,
    sizelength numeric,
    sizewidth numeric,
    sizeheight numeric
);


ALTER TABLE public."Size" OWNER TO postgres;

--
-- Name: Size_sizeid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Size" ALTER COLUMN sizeid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Size_sizeid_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Specification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Specification" (
    specificationid bigint NOT NULL,
    sizeid bigint,
    specificationweight numeric,
    specificationcount integer,
    specificationprice numeric
);


ALTER TABLE public."Specification" OWNER TO postgres;

--
-- Name: Specification_specificationid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Specification" ALTER COLUMN specificationid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Specification_specificationid_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Type" (
    typeid bigint NOT NULL,
    typename character varying
);


ALTER TABLE public."Type" OWNER TO postgres;

--
-- Name: Type_typeid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Type" ALTER COLUMN typeid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Type_typeid_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: User; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."User" (
    userid bigint NOT NULL,
    userinfoid bigint,
    authenticationid bigint,
    positionid integer
);


ALTER TABLE public."User" OWNER TO postgres;

--
-- Name: UserHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."UserHistory" (
    userhistoryid bigint NOT NULL,
    userid bigint,
    productid bigint,
    previousadressid bigint,
    newadressid bigint,
    userhistorytransitiontime timestamp without time zone
);


ALTER TABLE public."UserHistory" OWNER TO postgres;

--
-- Name: UserHistory_userhistoryid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."UserHistory" ALTER COLUMN userhistoryid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."UserHistory_userhistoryid_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: UserInfo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."UserInfo" (
    userinfoid bigint NOT NULL,
    userinfoname character varying,
    userinfosurname character varying,
    userinfopatronymic character varying,
    userinfophone character varying,
    userinfoemail character varying
);


ALTER TABLE public."UserInfo" OWNER TO postgres;

--
-- Name: UserInfo_userinfoid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."UserInfo" ALTER COLUMN userinfoid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."UserInfo_userinfoid_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: User_userid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."User" ALTER COLUMN userid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."User_userid_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Warehouse; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Warehouse" (
    warehouseid bigint NOT NULL,
    warehouseadressadress character varying,
    warehousenumber character varying,
    warehousesection character varying,
    warehouseshelf character varying,
    warehousecell character varying
);


ALTER TABLE public."Warehouse" OWNER TO postgres;

--
-- Name: Warehouse_warehouseid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Warehouse" ALTER COLUMN warehouseid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Warehouse_warehouseid_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: Authentication; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Authentication" (authenticationid, password) FROM stdin;
5	$2a$08$oqOmzBoMgiwaZVEhbuTtHexsPt5T/xXggsIICi52kzo2mfpERD7eu
\.


--
-- Data for Name: BankingCredentials; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."BankingCredentials" (bankingcredentialsid, bankingcredentialsie, bankingcredentialskpp, bankingcredentialsinn, bankingcredentialsbic, bankingcredentialskpo, bankingcredentialsogrn, bankingcredentialsfax, bankingcredentialsphone, bankingcredentialsbank) FROM stdin;
\.


--
-- Data for Name: Client; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Client" (clientid, clientname, bankingcredentialsid) FROM stdin;
\.


--
-- Data for Name: Dilivery; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Dilivery" (diliveryid, diliveryneeded, diliveryadress, diliverytime, diliverytypeid) FROM stdin;
\.


--
-- Data for Name: DiliveryType; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."DiliveryType" (diliverytypeid, diliverytypename) FROM stdin;
\.


--
-- Data for Name: Distributor; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Distributor" (distributorid, distributorname, bankingcredentialsid) FROM stdin;
1	Acer	\N
\.


--
-- Data for Name: Order; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Order" (orderid, orderdescription, ordertime, ordertotalprice, clientid, diliveryid) FROM stdin;
\.


--
-- Data for Name: OrderedProducts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."OrderedProducts" (orderedproductsid, orderid, productid, orderedproductscount) FROM stdin;
\.


--
-- Data for Name: Position; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Position" (positionid, positionname) FROM stdin;
2	User
3	New
1	Admin
\.


--
-- Data for Name: Product; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Product" (productid, warehouseid, typeid, distributorid, specificationid, productname, productarrival, productinwarehouse) FROM stdin;
1	1	1	1	1	Computer	2022-09-25 14:45:30	t
\.


--
-- Data for Name: Size; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Size" (sizeid, sizelength, sizewidth, sizeheight) FROM stdin;
1	10.1	10.1	10.1
\.


--
-- Data for Name: Specification; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Specification" (specificationid, sizeid, specificationweight, specificationcount, specificationprice) FROM stdin;
1	1	10.1	500	50000
\.


--
-- Data for Name: Type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Type" (typeid, typename) FROM stdin;
1	Tech
\.


--
-- Data for Name: User; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."User" (userid, userinfoid, authenticationid, positionid) FROM stdin;
3	3	5	1
\.


--
-- Data for Name: UserHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."UserHistory" (userhistoryid, userid, productid, previousadressid, newadressid, userhistorytransitiontime) FROM stdin;
\.


--
-- Data for Name: UserInfo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."UserInfo" (userinfoid, userinfoname, userinfosurname, userinfopatronymic, userinfophone, userinfoemail) FROM stdin;
3	userne	\N	\N	\N	email@example.com
\.


--
-- Data for Name: Warehouse; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Warehouse" (warehouseid, warehouseadressadress, warehousenumber, warehousesection, warehouseshelf, warehousecell) FROM stdin;
1	Ylyanovskay street	5A	1B	5	25
\.


--
-- Name: Authentication_authenticationid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Authentication_authenticationid_seq"', 5, true);


--
-- Name: BankingCredentials_bankingcredentialsid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."BankingCredentials_bankingcredentialsid_seq"', 1, false);


--
-- Name: Client_clientid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Client_clientid_seq"', 1, false);


--
-- Name: DiliveryType_diliverytypeid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."DiliveryType_diliverytypeid_seq"', 1, false);


--
-- Name: Dilivery_diliveryid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Dilivery_diliveryid_seq"', 1, false);


--
-- Name: Distributor_distributorid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Distributor_distributorid_seq"', 1, true);


--
-- Name: Order_orderid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Order_orderid_seq"', 1, false);


--
-- Name: OrderedProducts_orderedproductsid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."OrderedProducts_orderedproductsid_seq"', 1, false);


--
-- Name: Position_positionid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Position_positionid_seq"', 4, true);


--
-- Name: Product_productid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Product_productid_seq"', 3, true);


--
-- Name: Size_sizeid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Size_sizeid_seq"', 1, true);


--
-- Name: Specification_specificationid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Specification_specificationid_seq"', 1, true);


--
-- Name: Type_typeid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Type_typeid_seq"', 1, true);


--
-- Name: UserHistory_userhistoryid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."UserHistory_userhistoryid_seq"', 1, false);


--
-- Name: UserInfo_userinfoid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."UserInfo_userinfoid_seq"', 3, true);


--
-- Name: User_userid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."User_userid_seq"', 5, true);


--
-- Name: Warehouse_warehouseid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Warehouse_warehouseid_seq"', 1, true);


--
-- Name: BankingCredentials _BankingCredentials__pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BankingCredentials"
    ADD CONSTRAINT "_BankingCredentials__pk" PRIMARY KEY (bankingcredentialsid);


--
-- Name: Client _Client__pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Client"
    ADD CONSTRAINT "_Client__pk" PRIMARY KEY (clientid);


--
-- Name: DiliveryType _DiliveryType__pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DiliveryType"
    ADD CONSTRAINT "_DiliveryType__pk" PRIMARY KEY (diliverytypeid);


--
-- Name: Dilivery _Dilivery__pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Dilivery"
    ADD CONSTRAINT "_Dilivery__pk" PRIMARY KEY (diliveryid);


--
-- Name: Distributor _Distributor__pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Distributor"
    ADD CONSTRAINT "_Distributor__pk" PRIMARY KEY (distributorid);


--
-- Name: Order _Order__pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Order"
    ADD CONSTRAINT "_Order__pk" PRIMARY KEY (orderid);


--
-- Name: OrderedProducts _OrderedProducts__pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OrderedProducts"
    ADD CONSTRAINT "_OrderedProducts__pk" PRIMARY KEY (orderedproductsid);


--
-- Name: Position _Position__pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Position"
    ADD CONSTRAINT "_Position__pk" PRIMARY KEY (positionid);


--
-- Name: Product _Product__pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Product"
    ADD CONSTRAINT "_Product__pk" PRIMARY KEY (productid);


--
-- Name: Size _Size__pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Size"
    ADD CONSTRAINT "_Size__pk" PRIMARY KEY (sizeid);


--
-- Name: Specification _Specification__pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Specification"
    ADD CONSTRAINT "_Specification__pk" PRIMARY KEY (specificationid);


--
-- Name: Type _Type__pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Type"
    ADD CONSTRAINT "_Type__pk" PRIMARY KEY (typeid);


--
-- Name: UserHistory _UserHistory__pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserHistory"
    ADD CONSTRAINT "_UserHistory__pk" PRIMARY KEY (userhistoryid);


--
-- Name: UserInfo _UserInfo__pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserInfo"
    ADD CONSTRAINT "_UserInfo__pk" PRIMARY KEY (userinfoid);


--
-- Name: User _User__pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "_User__pk" PRIMARY KEY (userid);


--
-- Name: Warehouse _WarehouseAdress__pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Warehouse"
    ADD CONSTRAINT "_WarehouseAdress__pk" PRIMARY KEY (warehouseid);


--
-- Name: Authentication authentication_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Authentication"
    ADD CONSTRAINT authentication_pk PRIMARY KEY (authenticationid);


--
-- Name: Client _Client___BankingCredentials__FK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Client"
    ADD CONSTRAINT "_Client___BankingCredentials__FK" FOREIGN KEY (bankingcredentialsid) REFERENCES public."BankingCredentials"(bankingcredentialsid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: Dilivery _Dilivery___DiliveryType__FK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Dilivery"
    ADD CONSTRAINT "_Dilivery___DiliveryType__FK" FOREIGN KEY (diliverytypeid) REFERENCES public."DiliveryType"(diliverytypeid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: Distributor _Distributor___BankingCredentials__FK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Distributor"
    ADD CONSTRAINT "_Distributor___BankingCredentials__FK" FOREIGN KEY (bankingcredentialsid) REFERENCES public."BankingCredentials"(bankingcredentialsid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: Order _Order___Client__FK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Order"
    ADD CONSTRAINT "_Order___Client__FK" FOREIGN KEY (clientid) REFERENCES public."Client"(clientid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: Order _Order___Dilivery__FK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Order"
    ADD CONSTRAINT "_Order___Dilivery__FK" FOREIGN KEY (diliveryid) REFERENCES public."Dilivery"(diliveryid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: OrderedProducts _OrderedProducts___Order__FK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OrderedProducts"
    ADD CONSTRAINT "_OrderedProducts___Order__FK" FOREIGN KEY (orderid) REFERENCES public."Order"(orderid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: OrderedProducts _OrderedProducts___Product__FK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OrderedProducts"
    ADD CONSTRAINT "_OrderedProducts___Product__FK" FOREIGN KEY (productid) REFERENCES public."Product"(productid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: Product _Product___Distributor__FK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Product"
    ADD CONSTRAINT "_Product___Distributor__FK" FOREIGN KEY (distributorid) REFERENCES public."Distributor"(distributorid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: Product _Product___Specification__FK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Product"
    ADD CONSTRAINT "_Product___Specification__FK" FOREIGN KEY (specificationid) REFERENCES public."Specification"(specificationid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: Product _Product___Type__FK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Product"
    ADD CONSTRAINT "_Product___Type__FK" FOREIGN KEY (typeid) REFERENCES public."Type"(typeid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: Product _Product___Warehouse__FK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Product"
    ADD CONSTRAINT "_Product___Warehouse__FK" FOREIGN KEY (warehouseid) REFERENCES public."Warehouse"(warehouseid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: Specification _Specification___Size__FK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Specification"
    ADD CONSTRAINT "_Specification___Size__FK" FOREIGN KEY (sizeid) REFERENCES public."Size"(sizeid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: UserHistory _UserHistory___User__FK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserHistory"
    ADD CONSTRAINT "_UserHistory___User__FK" FOREIGN KEY (userid) REFERENCES public."User"(userid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: UserHistory _UserHistory___Warehouse__FK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserHistory"
    ADD CONSTRAINT "_UserHistory___Warehouse__FK" FOREIGN KEY (previousadressid) REFERENCES public."Warehouse"(warehouseid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: UserHistory _UserHistory___Warehouse__FK_1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserHistory"
    ADD CONSTRAINT "_UserHistory___Warehouse__FK_1" FOREIGN KEY (newadressid) REFERENCES public."Warehouse"(warehouseid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: User _User__Authentication_FK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "_User__Authentication_FK" FOREIGN KEY (authenticationid) REFERENCES public."Authentication"(authenticationid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: User _User___Position__FK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "_User___Position__FK" FOREIGN KEY (positionid) REFERENCES public."Position"(positionid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: User _User___UserInfo__FK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "_User___UserInfo__FK" FOREIGN KEY (userinfoid) REFERENCES public."UserInfo"(userinfoid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;


--
-- PostgreSQL database dump complete
--

